### PR TITLE
Build from python2 branch of katsdpdockerbase

### PR DESCRIPTION
**Pull request by bmerry**
In preparation for katsdpdockerbase master stripping out Python 2.

### CODE REVIEW

**Comment by bmerry** [comment]
The first build will probably fail because katsdpdockerbase:python2 will still be building.

**Comment by bmerry** [comment]
Urgh, looks like it has failed. So it is probably not related to the update of the Ubuntu base image but rather some other dependency.

**Comment by mauch** [comment]
Hmmm. Yes. Has much else changed in dockerbase? Because it's working on
imgr-com-3 with a docker-base-gpu from 2 months ago.

**Comment by bmerry** [comment]
The last change was on 16 December, and contim successfully built at that time. So my guess is that it's some Ubuntu package that has been updated.

**Comment by sratcliffe** [comment]
@bmerry - so what should we do in the meantime. Tom has a patch for the image issues, but they container will obviously fail to build. I guess we either roll back the base Ubuntu version or we run an override on master controller to use an earlier (Dec 16) build of katsdpcontim.

**Comment by bmerry** [comment]
Rolling back the base Ubuntu version didn't help (that's effectively what this PR does).

For now we should probably just roll back katsdpcontim by pulling in last year's production tag of katsdpcontim when assembling the new staging tag.

**Comment by sratcliffe** [comment]
Agreed - plan is to build with current staging as the base and override controller to latest and katsdpcontim to the previous production tag.

**Comment by bmerry** [comment]
Since the failure doesn't seem to be linked to the update of ubuntu base, I'm going to update the python2 branch of katsdpdockerbase to match master, and then merge this PR.

**Pull request merged**
